<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

</body>
<script>
    /**
     * Promise
     * 一、 Promise出现的原因
     *   1.为了解决异步回调的问题
     *   2.为了解决信任问题（第三方回调函数是不是只执行一次）
     *   3.为了解决回调执顺序问题（有的慢有的快）
     *   4.为了解决捕捉错误能力
     * 
     *二、 Promise
     *   1.概念：Promise是一个容器，里面存放着异步事件
     *   2.语法：Promise是一个对象，可以获取异步操作的消息
     *三、 特点
     *   1.他有三个状态 分别是：pedding（等待中），fulfilled（已成功），rejected（已失败）
     *   2.状态的变化：
     *      从等待中到已成功  pedding -> fulfilled
     *      从等待中到已失败  pedding -> rejected
     *   3.一旦状态确定，便不会再更改，状态凝固 -> resolved，无论是什么时候监听 也还是之前的样子
     *   4.Promise的返回值无论是不是Promise函数，最终都会被封装Promise函数进行返回，需要我们用then方法
     *   5.链式调用
     *四、 Promise和事件循环的区别
     *   1.事件循环一旦错过，不会再被监听到
     *   2.Promise状态凝固，永远都可以被监听到
     *五、 Promise的回调参数
     *    resolve -> 成功的回调
     *    reject  -> 失败的回调
     ***/

    // 实例化一个Promise
    const p = new Promise(function (resolve, reject) {
        setTimeout(function () {
            // let data ="123"
            // resolve(data)
            let data = "456"
            reject(data)
        })
    })
    p.then(res => {
        console.log(res, "成功回调");
    }).catch(err => {
        console.log(err, "失败回调");
    })
    console.log("------------------------------------");


    // 实例化一个Promise
    const a = new Promise(function (resolve, reject) {
        setTimeout(function () {
            // let data ="123"
            // resolve(data)
            let data = "456"
            reject(data)
        })
    })
    a.then(res => {
        console.log(res, "成功回调");
    }).catch(err => {
        console.log(err, "失败回调");
    })
    console.log("------------------------------------");


    // 实例化一个Promise
    const q = new Promise(function (resolve, reject) {
        setTimeout(function () {
            // let data ="123"
            // resolve(data)
            let data = "456"
            reject(data)
        })
    })
    q.then(res => {
        console.log(res, "成功回调");
    }).catch(err => {
        console.log(err, "失败回调");
    })
    console.log("------------------------------------");
</script>

</html>